services:
  backend:
    container_name: gribouille-backend
    build: ./backend
    environment:
      - PORT=3001
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/data:/app/data
    ports:
      - "3001:3001"
    restart: always

  frontend:
    container_name: gribouille-frontend
    build: ./frontend
    ports:
      - "8080:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: always
